# -*- coding: utf-8 -*-
"""SMTPemail sender.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vB7cwf9rInq6P1_ouAy_u4TxrAk1N0c5
"""

import smtplib

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

sender_email = "sender+email@mail.com"
sender_password = "wabsqstlctgygoad"
receiver_emails = ["receiver+email1@mail.com","receiver+email2@mail.com"]

server = smtplib.SMTP_SSL('smtp.googlemail.com', 465)
server.login(sender_email, sender_password)

for receiver_email in receiver_emails:
    msg = MIMEMultipart('alternative')
    msg['Subject'] = "Test mail"
    msg['From'] = sender_email
    msg['To'] = receiver_email

    html = """
        <h1>Hello world</h1>
    """
    msg.attach(MIMEText(html, 'html'))

    server.sendmail(sender_email, receiver_email, msg.as_string())

server.quit()